<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = new DateTime();
        $items = [
            // Objects
            [
                'name' => 'Almofada',
                'nameEN' => 'Pillow',
                'price' => null,
                'type' => 'O',
                'category' => 'room',
                'stock' => 20,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Cobertor',
                'nameEN' => 'Blanket',
                'price' => null,
                'type' => 'O',
                'category' => 'room',
                'stock' => 10,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Toalha',
                'nameEN' => 'Towel',
                'price' => null,
                'type' => 'O',
                'category' => 'bathroom',
                'stock' => 30,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Papel Higiénico',
                'nameEN' => 'Toilet Paper',
                'price' => null,
                'type' => 'O',
                'category' => 'bathroom',
                'stock' => 30,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Gel de Duche',
                'nameEN' => 'Shower Gel',
                'price' => null,
                'type' => 'O',
                'category' => 'bathroom',
                'stock' => 50,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Champô',
                'nameEN' => 'Shampoo',
                'price' => null,
                'type' => 'O',
                'category' => 'bathroom',
                'stock' => 50,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Adapatador de Tomada',
                'nameEN' => 'Plug Adapter',
                'price' => null,
                'type' => 'O',
                'category' => 'other',
                'stock' => 10,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Jornal do Dia',
                'nameEN' => 'Daily Newspaper',
                'price' => null,
                'type' => 'O',
                'category' => 'other',
                'stock' => 20,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            // Foods
            [
                'name' => 'Água (33cl)',
                'nameEN' => 'Water (33cl)',
                'price' => 1,
                'type' => 'F',
                'category' => 'drink',
                'stock' => 15,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Coca-Cola (33cl)',
                'nameEN' => 'Coca-Cola (33cl)',
                'price' => 2,
                'type' => 'F',
                'category' => 'drink',
                'stock' => 15,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Garrafa de Champanhe',
                'nameEN' => 'Bottle of Champagne',
                'price' => 15,
                'type' => 'F',
                'category' => 'drink',
                'stock' => 10,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Café',
                'nameEN' => 'Coffee',
                'price' => 0.85,
                'type' => 'F',
                'category' => 'drink',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Tosta Mista',
                'nameEN' => 'Toasted Sandwich',
                'price' => 3.5,
                'type' => 'F',
                'category' => 'snack',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Sandes Mista',
                'nameEN' => 'Mixed Sandwich',
                'price' => 3,
                'type' => 'F',
                'category' => 'snack',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Pequeno-Almoço Continental',
                'nameEN' => 'Continental Breakfast',
                'price' => 6,
                'type' => 'F',
                'category' => 'breakfast',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Ovos Mexidos com Bacon',
                'nameEN' => 'Scrambled Eggs with Bacon',
                'price' => 5.5,
                'type' => 'F',
                'category' => 'breakfast',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Panquecas com Toppings',
                'nameEN' => 'Pancakes with Toppings',
                'price' => 5,
                'type' => 'F',
                'category' => 'breakfast',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Tigela de Aveia com Frutas',
                'nameEN' => 'Oatmeal Bowl with Fruits',
                'price' => 3.5,
                'type' => 'F',
                'category' => 'breakfast',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Sumo de Laranja Natural',
                'nameEN' => 'Natural Orange Juice',
                'price' => 2.5,
                'type' => 'F',
                'category' => 'breakfast',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Salada Caesar com Frango Grelhado',
                'nameEN' => 'Caesar Salad with Grilled Chicken',
                'price' => 10,
                'type' => 'F',
                'category' => 'lunch',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Massa Pesto com Tomates Secos',
                'nameEN' => 'Pesto Pasta with Sundried Tomatoes',
                'price' => 11.5,
                'type' => 'F',
                'category' => 'lunch',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Hambúrguer Vegetariano',
                'nameEN' => 'Vegetarian Burger',
                'price' => 9,
                'type' => 'F',
                'category' => 'lunch',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Wrap de Frango com Guacamole',
                'nameEN' => 'Chicken Wrap with Guacamole',
                'price' => 8.5,
                'type' => 'F',
                'category' => 'lunch',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Bife com Molho de Cogumelos',
                'nameEN' => 'Steak with Mushroom Sauce',
                'price' => 15,
                'type' => 'F',
                'category' => 'dinner',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Salmão Grelhado com Molho de Limão',
                'nameEN' => 'Grilled Salmon with Lemon Sauce',
                'price' => 15,
                'type' => 'F',
                'category' => 'dinner',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Risoto de Cogumelos Porcini',
                'nameEN' => 'Porcini Mushroom Risotto',
                'price' => 13,
                'type' => 'F',
                'category' => 'dinner',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
            [
                'name' => 'Frango Assado com Batatas',
                'nameEN' => 'Roasted Chicken with Potatoes',
                'price' => 12.5,
                'type' => 'F',
                'category' => 'dinner',
                'stock' => null,
                'created_at' => '2023-01-01 00:00',
                'updated_at' => $now,
            ],
        ];

        DB::table('items')->insert($items);
    }
}
